### ISSUE TITLE
System.ArgumentNullException: Value cannot be null

### ISSUE THREAD

**Issue by hoisel** [dpaquette/EntityFramework.Seeder#7]
Hi,
I'm getting in this error:
`Running Seed method.
System.Exception: Error Seeding DbSet<Itix.Opme.Domain.Model.Procedimento>: System.ArgumentNullException: Value cannot be null.
Parameter name: stream
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at System.IO.StreamReader..ctor(Stream stream)
   at EntityFramework.Seeder.Seeder.SeedFromStream[T](IDbSet`1 dbSet, Stream stream, Expression1 identifierExpression, CsvColumnMapping`1[] additionalMapping) ---> System.ArgumentNullException: Value cannot be null.`

Thanks

**Comment by ghost** [comment]
+req , i have too problem

**Comment by pinaki1234** [comment]
That's because it's not able to load the file. Please check how you attach the file - please check the attachment from this sample project https://github.com/dpaquette/SeedingDatabaseFromCSV. Yes this is a hell ambiguous message and you can waste days on this. Hope this helps.

**Comment by dpaquette** [comment]
In most cases, I haven't been able to get proper error messages to report through to the Package Manager Console. This might be one of those areas where I can actually display a better message
